"""Render CITATIONS.md from CSL-JSON using the vendored CSL style."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import fire
from citeproc import (
    Citation,
    CitationItem,
    CitationStylesBibliography,
    CitationStylesStyle,
    formatter,
)
from citeproc.source.json import CiteProcJSON

# ==== paths ====

REPO_ROOT = Path(__file__).resolve().parents[1]
REFERENCES = REPO_ROOT / "docs" / "references.json"
STYLE = REPO_ROOT / "docs" / "csl" / "bioinformatics.csl"
OUTPUT = REPO_ROOT / "CITATIONS.md"

HEADER = """# Citations

Generated by `scripts/render_citations.py` from `docs/references.json` using
`docs/csl/bioinformatics.csl`. Do not edit by hand; edit the JSON and re-render.

Identifiers are listed separately because the citation style does not emit them.
"""

logger = logging.getLogger(__name__)


# ==== rendering ====


def _load_entries(references: Path) -> list[dict[str, object]]:
    return json.loads(references.read_text(encoding="utf-8"))


def _render(
    entries: list[dict[str, object]],
    style_path: Path,
) -> tuple[list[str], list[str]]:
    """Return (in-text citations, bibliography entries) in input order."""
    style = CitationStylesStyle(str(style_path), validate=False)
    bibliography = CitationStylesBibliography(
        style,
        CiteProcJSON(entries),
        formatter.plain,
    )

    citations = [Citation([CitationItem(str(entry["id"]))]) for entry in entries]
    for citation in citations:
        bibliography.register(citation)

    in_text = [
        str(bibliography.cite(citation, lambda item: None)) for citation in citations
    ]
    rendered = [str(item) for item in bibliography.bibliography()]
    return in_text, rendered


def _identifier_cell(entry: dict[str, object]) -> str:
    parts = []
    if doi := entry.get("DOI"):
        parts.append(f"doi:{doi}")
    if pmid := entry.get("PMID"):
        parts.append(f"PMID {pmid}")
    if url := entry.get("URL"):
        parts.append(str(url))
    return "; ".join(parts) or "-"


def _build_document(entries: list[dict[str, object]], style_path: Path) -> str:
    in_text, rendered = _render(entries, style_path)

    lines = [HEADER, "\n## References\n"]
    for entry, citation in zip(entries, in_text, strict=True):
        lines.append(f"- **{citation}** — {entry.get('note', '')}".rstrip(" —"))

    lines.append("\n## Full entries\n")
    lines.extend(f"{item}\n" for item in sorted(rendered))

    lines.append("\n## Identifiers\n")
    lines.append("| Citation | Identifiers |")
    lines.append("| --- | --- |")
    pairs = sorted(zip(entries, in_text, strict=True), key=lambda pair: pair[1])
    for entry, citation in pairs:
        lines.append(f"| {citation} | {_identifier_cell(entry)} |")

    return "\n".join(lines) + "\n"


# ==== cli ====


class Citations:
    """Render and inspect the project's citation list."""

    def render(self, *, check: bool = False) -> str:
        """Write CITATIONS.md from docs/references.json.

        Args:
            check: Report whether the file is current instead of writing it.
        """
        entries = _load_entries(REFERENCES)
        document = _build_document(entries, STYLE)

        if check:
            if not OUTPUT.exists():
                return "CITATIONS.md missing; run render"
            current = OUTPUT.read_text(encoding="utf-8")
            return "up to date" if current == document else "out of date; run render"

        OUTPUT.write_text(document, encoding="utf-8")
        return f"wrote {OUTPUT.name} ({len(entries)} references)"

    def show(self) -> str:
        """Print rendered citations without writing any file."""
        entries = _load_entries(REFERENCES)
        in_text, rendered = _render(entries, STYLE)
        pairs = (f"{c}\n    {r}" for c, r in zip(in_text, rendered, strict=True))
        return "\n".join(pairs)


def main() -> None:
    """Entry point for the citation renderer."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    fire.Fire(Citations)


if __name__ == "__main__":
    main()
